development:
  adapter: postgresql
  encoding: unicode
  database: tw_assets_manager_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tw_assets_manager_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tw_assets_manager_production
  pool: 5
  username:
  password:
