development:
  adapter: postgresql
  encoding: unicode
  database: tw_assets_manager_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tw_assets_manager_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tw_asset_manager
  pool: 5
  username: tw_asset_manager
  password:
